FROM python:3.7-alpine
WORKDIR /code

COPY forwarder/requirements.txt requirements.txt

RUN apk add --no-cache --virtual .deps gcc musl-dev linux-headers \
    && pip install -r requirements.txt \
    && apk del --no-cache .deps \
    && rm -rf /var/cache/apk/*

COPY ./forwarder .

CMD ["python", "./forwarder.py"]