version: '3.7'
services:
  gamemaster:
    image: localhost:5000/dockertest_gamemaster:latest
    build:
      context: .
      dockerfile: Dockerfile.gamemaster
    networks:
      - network1
      - network2
    hostname: gamemaster
    ports:
      - "5000:5000"

  sheep1:
    image: localhost:5000/dockertest_sheep1:latest
    build:
      context: .
      dockerfile: Dockerfile.sheep
    networks:
      - network1
    hostname: sheep1

  sheep2:
    image: localhost:5000/dockertest_sheep1:latest
    build:
      context: .
      dockerfile: Dockerfile.sheep
    networks:
      - network1
      - network2
    hostname: sheep2

  sheep3:
    image: localhost:5000/dockertest_sheep1:latest
    build:
      context: .
      dockerfile: Dockerfile.sheep
    networks:
      - network2
    hostname: sheep3

networks:
  network1:
    driver: bridge
    ipam:
      driver: default
  network2:
    internal: true
#      config:
#        - subnet: "172.16.0.0/24"
#    driver: overlay
#    internal: true
#    driver: custom-driver-2
#https://forums.docker.com/t/internal-network-between-containers-without-external-network-access/41751/8
