version: '3.7'
services:
  gamemaster:
    image: localhost:5000/dockertest_gamemaster:latest
    build:
      context: .
      dockerfile: Dockerfile.gamemaster
    networks:
      - network1
    hostname: gamemaster
    ports:
      - "5000:5000"

  sheep1:
    image: localhost:5000/dockertest_sheep1:latest
    build:
      context: .
      dockerfile: Dockerfile.sheep
    networks:
      - network1
    hostname: sheep1

#  sheep2:
#    build:
#      context: .
#      dockerfile: Dockerfile.sheep
#    networks:
#      - network1
#    hostname: sheep2

#  sheep3:
#    build:
#      context: .
#      dockerfile: Dockerfile.sheep
#    networks:
#      - network1
#    hostname: sheep3

networks:
  network1:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.16.0.0/24"

#    driver: overlay
#    internal: true
#  network2:
#    driver: custom-driver-2
#https://forums.docker.com/t/internal-network-between-containers-without-external-network-access/41751/8
