FROM python:3.7-alpine
WORKDIR /code

ENV FLASK_APP=app.py \
    FLASK_RUN_HOST=0.0.0.0

COPY gamemaster/requirements.txt requirements.txt

RUN apk add make gcc linux-headers python3-dev musl-dev libffi-dev openssl-dev libsodium-dev docker
RUN pip install -r requirements.txt 

COPY ./gamemaster .
COPY docker-compose.sheep.yml .

EXPOSE 5000

CMD ["flask", "run"]