FROM python:3.7-alpine
WORKDIR /code

RUN apk add --no-cache --virtual .deps gcc musl-dev linux-headers \
    && pip install -r requirements.txt \
    && apk del --no-cache .deps \
    && rm -rf /var/cache/apk/* \
    && touch /var/log/syslog

COPY sheep/requirements.txt requirements.txt
COPY ./sheep .

#USER
CMD ["python", "./logger.py"]