FROM python:3.7-alpine
WORKDIR /code
RUN apk add --no-cache gcc musl-dev linux-headers
COPY sheep/requirements.txt requirements.txt
RUN pip install -r requirements.txt
COPY ./sheep .
RUN touch /var/log/syslog
CMD ["python", "./logger.py"]