FROM python:3.7-alpine
WORKDIR /code

COPY wolf/requirements.txt requirements.txt
COPY ./wolf .

RUN apk add --no-cache --virtual .deps gcc musl-dev linux-headers \
    && pip install -r requirements.txt \
    && apk del --no-cache .deps \
    && rm -rf /var/cache/apk/*

CMD ["python", "./forwarder.py"]