version: '3.7'
services:
  sheep1:
    image: sandbox_entry_sheep:latest
    build:
      context: .
      dockerfile: Dockerfile.entry_sheep
    networks:
      - network1
    hostname: sheep1

  sheep2:
    image: sandbox_sheep1:latest
    build:
      context: .
      dockerfile: Dockerfile.sheep
    networks:
      - network1
      - network2
    hostname: sheep2

  sheep3:
    image: sandbox_sheep1:latest
    build:
      context: .
      dockerfile: Dockerfile.sheep
    networks:
      - network2
    hostname: sheep3

  wolf:
    image: sandbox_wolf:latest
    build:
      context: .
      dockerfile: Dockerfile.wolf
    networks:
      - network2
      - network1
      - network_master

networks:
  network1:
    internal: true
  network2:
    internal: true
  network_master:
    external: true