FROM python:3.7-alpine
WORKDIR /code
RUN apk add --no-cache gcc musl-dev linux-headers
COPY forwarder/requirements.txt requirements.txt
RUN pip install -r requirements.txt
COPY ./forwarder .
CMD ["python", "./forwarder.py"]