FROM python:3.7-alpine
WORKDIR /code

ENV FLASK_APP=app.py \
    FLASK_RUN_HOST=0.0.0.0

COPY wolf/requirements.txt requirements.txt
COPY ./wolf .
COPY docker-compose.sheep.yml .

RUN apk add --no-cache --virtual .deps make gcc linux-headers python3-dev musl-dev libffi-dev openssl-dev libsodium-dev \
    && pip install -r requirements.txt \
    && apk del --no-cache .deps \
    && rm -rf /var/cache/apk/*

EXPOSE 5000

CMD ["flask", "run"]